# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # --------------------------------------------------------------------------
  # General hooks
  # --------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # --------------------------------------------------------------------------
  # Spelling
  # --------------------------------------------------------------------------
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.3
    hooks:
      - id: cspell # Spell check changed files
        exclude: ^\.vscode/extensions\.json$|^vsc-extension-quickstart\.md$
